export const formColumns = [
  {
    label: "活动名称",
    name: "input",
    type: "input",
    rules: [],
    width: 300,
  },
  {
    label: "活动选择",
    name: "select",
    type: "select",
    rules: [],
    options: [
      { label: "篮球", value: "lanqiu" },
      { label: "足球", value: "zuqiu" },
    ],
    width: 300,
  },
  {
    label: "活动区域",
    name: "area",
    type: "area",
    rules: [],
    options: [
      { label: "Zone one", value: "shanghai" },
      { label: "Zone two", value: "beijing" },
    ],
    width: 300,
  },
  {
    label: "活动时间",
    name: "datetime",
    type: "datetime",
    startProp: "date1",
    endProp: "date2",
    rules: [],
    width: 300,
  },
  {
    label: "活动时间2",
    name: "datetimerange",
    type: "datetimerange",
    startProp: "date1",
    endProp: "date2",
    rules: [],
    width: 300,
  },
  {
    label: "活动时间3",
    name: "date",
    type: "date",
    startProp: "date1",
    endProp: "date2",
    rules: [],
    width: 300,
  },
  {
    label: "活动时间4",
    name: "daterange",
    type: "daterange",
    startProp: "date1",
    endProp: "date2",
    rules: [],
    width: 300,
  },
  {
    label: "即时配送",
    name: "switch",
    type: "switch",
    defaultValue: false, // 初始默认值
    width: 300,
  },
  {
    label: "活动类型",
    name: "checkbox",
    type: "checkbox",
    rules: [],
    options: [
      { label: "茶话会", value: "cha" },
      { label: "漫展", value: "man" },
      { label: "运动", value: "yun" },
    ],
    width: 300,
  },
  {
    label: "资源类型",
    name: "radio",
    type: "radio",
    rules: [],
    options: [
      { label: "中国", value: "china" },
      { label: "日本", value: "janpan" },
      { label: "美国", value: "amira" },
      { label: "澳大利亚", value: "ostra" },
    ],
    width: 300,
  },
  {
    label: "备注",
    name: "textarea",
    type: "textarea",
    rules: [],
    width: 300,
  },
];
