export const formColumns = [
  {
    label: "活动名称",
    name: "input",
    type: "input",
    placeholder: "请输入活动名称",
    rules: [],
  },
  {
    label: "活动选择",
    name: "select",
    type: "select",
    placeholder: "please select your zone",
    rules: [],
    options: [
      { label: "篮球", value: "lanqiu" },
      { label: "足球", value: "zuqiu" },
    ],
  },
  {
    label: "活动区域",
    name: "areaSelect",
    type: "areaSelect",
    placeholder: "please select your zone",
    rules: [],
    options: [
      { label: "Zone one", value: "shanghai" },
      { label: "Zone two", value: "beijing" },
    ],
  },
  {
    label: "活动时间",
    name: "datetime",
    type: "datetime",
    startProp: "date1",
    endProp: "date2",
    startPlaceholder: "Pick a date",
    endPlaceholder: "Pick a time",
    rules: [],
  },
  {
    label: "活动时间2",
    name: "datetimerange",
    type: "datetimerange",
    startProp: "date1",
    endProp: "date2",
    startPlaceholder: "Pick a date",
    endPlaceholder: "Pick a time",
    rules: [],
  },
  {
    label: "活动时间3",
    name: "date",
    type: "date",
    startProp: "date1",
    endProp: "date2",
    startPlaceholder: "Pick a date",
    endPlaceholder: "Pick a time",
    rules: [],
  },
  {
    label: "活动时间4",
    name: "daterange",
    type: "daterange",
    startProp: "date1",
    endProp: "date2",
    startPlaceholder: "Pick a date",
    endPlaceholder: "Pick a time",
    rules: [],
  },
  {
    label: "即时配送",
    name: "switch",
    type: "switch",
    defaultValue: false, // 初始默认值
  },
  {
    label: "活动类型",
    name: "checkbox",
    type: "checkbox",
    rules: [],
    options: [
      { label: "Online activities", value: "Online activities" },
      { label: "Promotion activities", value: "Promotion activities" },
      { label: "Offline activities", value: "Offline activities" },
      { label: "Simple brand exposure", value: "Simple brand exposure" },
    ],
  },
  {
    label: "资源类型",
    name: "radio",
    type: "radio",
    rules: [],
    options: [
      { label: "Sponsor", value: "Sponsor" },
      { label: "Venue", value: "Venue" },
    ],
  },
  {
    label: "活动形式",
    name: "textarea",
    type: "textarea",
    placeholder: "请输入活动形式",
    rules: [],
  },
];
